/**
 * Stable, public-facing subset of the NH48 catalog used for photo labels.
 * The source is kept local so builds do not depend on the legacy endpoint.
 */
export const NH48_DATA_SOURCE = "https://nh48.info/data/nh48.json";

export const NH48_RANGES = Object.freeze({
  "Bondcliff": "Pemigewasset Wilderness",
  "Cannon Mountain": "Kinsman Range",
  "Carter Dome": "Carter-Moriah Range",
  "Middle Carter Mountain": "Carter-Moriah Range",
  "Middle Tripyramid": "Sandwich / Waterville Range",
  "Mount Adams": "Presidential Range",
  "Mount Carrigain": "Pemigewasset Wilderness",
  "Mount Eisenhower": "Presidential Range",
  "Mount Field": "Willey Range",
  "Mount Garfield": "Franconia Range",
  "Mount Hale": "Twin Range",
  "Mount Hancock - North Peak.": "Pemigewasset Wilderness",
  "Mount Isolation": "Presidential Range",
  "Mount Jackson": "Presidential Range",
  "Mount Jefferson": "Presidential Range",
  "Mount Lafayette": "Franconia Range",
  "Mount Liberty": "Franconia Range",
  "Mount Lincoln": "Franconia Range",
  "Mount Madison": "Presidential Range",
  "Mount Monroe": "Presidential Range",
  "Mount Moosilauke": "Kinsman Range",
  "Mount Moriah": "Carter-Moriah Range",
  "Mount Passaconaway": "Sandwich / Waterville Range",
  "Mount Pierce": "Presidential Range",
  "Mount Tecumseh": "Sandwich / Waterville Range",
  "Mount Tom": "Willey Range",
  "Mount Washington": "Presidential Range",
  "Mount Waumbek": "Pilot–Pliny Range",
  "Mount Whiteface": "Sandwich / Waterville Range",
  "Mount Willey": "Willey Range",
  "North Tripyramid": "Sandwich / Waterville Range",
  "North Twin Mountain": "Twin Range",
  "Owl's Head": "Pemigewasset Wilderness",
  "South Carter Mountain": "Carter-Moriah Range",
  "South Kinsman Mountain": "Kinsman Range",
  "South Tripyramid": "Sandwich / Waterville Range",
  "South Twin Mountain": "Twin Range",
  "West Bond": "Pemigewasset Wilderness",
  "Wildcat Mountain - A Peak.": "Carter-Moriah Range",
  "Zealand Mountain": "Twin Range",
  "Galehead Mountain": "Twin Range",
  "Mount Bond": "Pemigewasset Wilderness",
  "Mount Cabot": "Pilot–Pliny Range",
  "Mount Flume": "Franconia Range",
  "Mount Hancock - South Peak.": "Pemigewasset Wilderness",
  "Mount Osceola": "Sandwich / Waterville Range",
  "Mount Osceola - East Peak.": "Sandwich / Waterville Range",
  "North Kinsman Mountain": "Kinsman Range",
  "Wildcat Mountain - D Peak.": "Carter-Moriah Range",
});
